### GET /v1/greeting
GET http://localhost:5000/v1/greeting

### POST /v1/joke
POST http://localhost:5000/v1/joke
Content-Type: application/json

{
    "topic": "Cats"
}

### POST /v1/products
POST http://localhost:5000/v1/products
Content-Type: application/json

{
    "category": "Electronics",
    "count": 2
}